# Generated by Django 3.1.4 on 2020-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20201223_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('mobile', 'mobile'), ('Tech', 'Tech'), ('comedy', 'comedy'), ('film_making', 'film_making'), ('cooking', 'cooking'), ('gaming', 'gaming'), ('vlog', 'vlog'), ('news', 'news'), ('adult', 'adult'), ('cartoon', 'cartoon')], max_length=255),
        ),
    ]
